
Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
    config.vm.box_url = "https://app.vagrantup.com/generic/boxes/centos8/versions/4.1.4/providers/virtualbox.box"
  
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
      vb.cpus = 1
    end
  
    config.vm.define "ojouboutS" do |server|
      server.vm.hostname = "ojouboutS"
      server.vm.synced_folder ".", "/vagrant"
      server.vm.provider "virtualbox" do |vb|
        vb.customize ['modifyvm', :id, "--name", "ojouboutS"]
      end
      server.vm.network "private_network", ip: "192.168.42.110"

  
    #   server.vm.provision "shell", path: "scripts/server_script.sh"
  
    end
  
    config.vm.define "ojouboutSW" do |server_worker|
      server_worker.vm.hostname = "ojouboutSW"
      server_worker.vm.synced_folder ".", "/vagrant"
      server_worker.vm.provider "virtualbox" do |vb|
        vb.customize ['modifyvm', :id, "--name", "ojouboutSW"]
      end
      server_worker.vm.network "private_network", ip: "192.168.42.111"
  
  
    #   server_worker.vm.provision "shell", path: "scripts/worker_script.sh"
  
    end
  end