
Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
  
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = 2
    end
  
    config.vm.define "ojouboutS" do |server|
      server.vm.hostname = "ojouboutS"
      server.vm.synced_folder ".", "/vagrant", type: 'virtualbox'
      server.vm.provider "virtualbox" do |vb|
        vb.customize ['modifyvm', :id, "--name", "ojouboutS"]
      end
      server.vm.network "private_network", ip: "192.168.42.110"

  
      server.vm.provision "shell", path: "scripts/server.sh"
  
    end
  
  end