
Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
      
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
  
    end
  
    config.vm.define "ojouboutS" do |server|
      server.vm.hostname = "ojouboutS"
      server.vm.synced_folder ".", "/vagrant", type: 'virtualbox'
      server.vm.provider "virtualbox" do |vb|
        vb.customize ['modifyvm', :id, "--name", "ojouboutS"]
      end
      server.vm.network "private_network", ip: "192.168.42.110"

  
      server.vm.provision "shell", path: "scripts/server.sh"
  
    end
  
    config.vm.define "ojouboutSW" do |server_worker|
      server_worker.vm.hostname = "ojouboutSW"
      server_worker.vm.synced_folder ".", "/vagrant", type: 'virtualbox'
      server_worker.vm.provider "virtualbox" do |vb|
        vb.customize ['modifyvm', :id, "--name", "ojouboutSW"]
      end
      server_worker.vm.network "private_network", ip: "192.168.42.111"
  
  
      server_worker.vm.provision "shell", path: "scripts/worker.sh"
  
    end
  end